config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :nominations
  resources :stats
  resources :users

  root 'nominations#index'
 
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/nomination.rb
class Nomination < ApplicationRecord
end

app/controllers/nominations_controller.rb
class NominationsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_nomination, only: %i[ show edit update destroy ]

  # GET /nominations or /nominations.json
  def index
    @nominations = Nomination.all.order('created_at DESC')
  end

  # GET /nominations/1 or /nominations/1.json
  def show
  end

  # GET /nominations/new
  def new
    @nomination = Nomination.new
  end

  # GET /nominations/1/edit
  def edit
  end

  # POST /nominations or /nominations.json
  def create
  
    @nomination = Nomination.new(nomination_params)
    thisUser = User.find_by(fName: params[:receiverName])
    @nomination.user_id = thisUser.id
    @nomination.senderId = current_user.id
    @nomination.senderName = current_user.fName

    respond_to do |format|
      if @nomination.save
        format.html { redirect_to nomination_url(@nomination), notice: "Nomination was successfully created." }
        format.json { render :show, status: :created, location: @nomination }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @nomination.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /nominations/1 or /nominations/1.json
  def update
    respond_to do |format|
      if @nomination.update(nomination_params)
        format.html { redirect_to nomination_url(@nomination), notice: "Nomination was successfully updated." }
        format.json { render :show, status: :ok, location: @nomination }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @nomination.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /nominations/1 or /nominations/1.json
  def destroy
    @nomination.destroy

    respond_to do |format|
      format.html { redirect_to nominations_url, notice: "Nomination was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_nomination
      @nomination = Nomination.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def nomination_params
      params.require(:nomination).permit(:nom_type, :senderId, :senderName, :user_id, :receiverName, :receiverImage, :body)
    end
end

app/helpers/nominations_helper.rb
module NominationsHelper
end

app/views/nominations/_form.html.erb
<%= form_with(model: nomination) do |form| %>
  <% if nomination.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(nomination.errors.count, "error") %> prohibited this nomination from being saved:</h2>

      <ul>
        <% nomination.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nom_type %>
    <%= form.text_field :nom_type %>
  </div>


  <div class="field">
    <%= form.label :receiverName %>
    <%= form.text_field :receiverName %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_field :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/nominations/edit.html.erb
<h1>Editing Nomination</h1>

<%= render 'form', nomination: @nomination %>

<%= link_to 'Show', @nomination %> |
<%= link_to 'Back', nominations_path %>

app/views/nominations/index.html.erb
<p id="notice"><%= notice %></p>

<!-- ======= Nomination Section ======= -->
<section id="nom" class="nom-section">

      <div class="container" >
        <div class="text-center">
          <a class="nom-btn" href="/nominations/new" >Send Shoutout</a>
        </div>
      </div>
  <div id="nom-container" class="home-page-notifications">
  
    <% @nominations.each do |nomination| %>
      <div class="nom-holder" > 
      <div class="container mt-2">
      <div class="row">
        <div class="col-md-2">
          <img src="https://img.freepik.com/free-photo/headshot-charismatic-pleasant-friendly-european-woman-short-chestnut-haircut-smiling-positive-feeling-happy-upbeat-enjoying-lifes-casually-talking-friends-amused-cheerful-standing-white-background_176420-34680.jpg" alt="Profile Picture" class="nom-image">
        </div>
        <div class="col-md-8">
          <h2><%= nomination.receiverName %></h2>
          <p><%= nomination.body %></p>
        </div>
        <div class="col-md-2">
        <% if nomination.nom_type == "mvp"%>
        <img src="https://www.creativefabrica.com/wp-content/uploads/2022/11/10/MVP-gold-medal-award-on-white-background-Graphics-45934671-1-1-580x387.jpg" alt="Profile Picture" class="nom-image">
        <% else %>
        <img src="https://renegade-promotions.com/wp-content/uploads/2021/05/148-1485119_shout-out-png-download-shout-out-transparent-png.png" alt="Profile Picture" class="nom-image">
        <% end %>
        
        </div>
      </div>
    </div>
      </div>
    <% end %>
  </div>
</section>

app/views/nominations/new.html.erb
<h1>New Nomination</h1>

<%= render 'form', nomination: @nomination %>

<%= link_to 'Back', nominations_path %>

app/views/nominations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Type:</strong>
  <%= @nomination.nom_type %>
</p>

<p>
  <strong>Senderid:</strong>
  <%= @nomination.senderId %>
</p>

<p>
  <strong>Sendername:</strong>
  <%= @nomination.senderName %>
</p>

<p>
  <strong>Receivername:</strong>
  <%= @nomination.receiverName %>
</p>

<p>
  <strong>Receiverimage:</strong>
  <%= @nomination.receiverImage %>
</p>

<p>
  <strong>Body:</strong>
  <%= @nomination.body %>
</p>

<%= link_to 'Edit', edit_nomination_path(@nomination) %> |
<%= link_to 'Back', nominations_path %>