config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :nominations
  resources :stats
  resources :users

  root 'nominations#index'
 
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/stat.rb
class Stat < ApplicationRecord
end

app/controllers/stats_controller.rb
class StatsController < ApplicationController
  before_action :set_stat, only: %i[ show edit update destroy ]

  # GET /stats or /stats.json
  def index
    @stats = Stat.all
  end

  # GET /stats/1 or /stats/1.json
  def show
  end

  # GET /stats/new
  def new
    @stat = Stat.new
  end

  # GET /stats/1/edit
  def edit
  end

  # POST /stats or /stats.json
  def create
    @stat = Stat.new(stat_params)

    respond_to do |format|
      if @stat.save
        format.html { redirect_to stat_url(@stat), notice: "Stat was successfully created." }
        format.json { render :show, status: :created, location: @stat }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @stat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stats/1 or /stats/1.json
  def update
    respond_to do |format|
      if @stat.update(stat_params)
        format.html { redirect_to stat_url(@stat), notice: "Stat was successfully updated." }
        format.json { render :show, status: :ok, location: @stat }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @stat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stats/1 or /stats/1.json
  def destroy
    @stat.destroy

    respond_to do |format|
      format.html { redirect_to stats_url, notice: "Stat was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stat
      @stat = Stat.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def stat_params
      params.require(:stat).permit(:userId, :nomsSent, :nomsReceived, :mvpWins)
    end
end

app/helpers/stats_helper.rb
module StatsHelper
end

app/views/stats/_form.html.erb
<%= form_with(model: stat) do |form| %>
  <% if stat.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(stat.errors.count, "error") %> prohibited this stat from being saved:</h2>

      <ul>
        <% stat.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :userId %>
    <%= form.number_field :userId %>
  </div>

  <div class="field">
    <%= form.label :nomsSent %>
    <%= form.number_field :nomsSent %>
  </div>

  <div class="field">
    <%= form.label :nomsReceived %>
    <%= form.number_field :nomsReceived %>
  </div>

  <div class="field">
    <%= form.label :mvpWins %>
    <%= form.number_field :mvpWins %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/stats/edit.html.erb
<h1>Editing Stat</h1>

<%= render 'form', stat: @stat %>

<%= link_to 'Show', @stat %> |
<%= link_to 'Back', stats_path %>

app/views/stats/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Stats</h1>

<table>
  <thead>
    <tr>
      <th>Userid</th>
      <th>Nomssent</th>
      <th>Nomsreceived</th>
      <th>Mvpwins</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stats.each do |stat| %>
      <tr>
        <td><%= stat.userId %></td>
        <td><%= stat.nomsSent %></td>
        <td><%= stat.nomsReceived %></td>
        <td><%= stat.mvpWins %></td>
        <td><%= link_to 'Show', stat %></td>
        <td><%= link_to 'Edit', edit_stat_path(stat) %></td>
        <td><%= link_to 'Destroy', stat, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Stat', new_stat_path %>

app/views/stats/new.html.erb
<h1>New Stat</h1>

<%= render 'form', stat: @stat %>

<%= link_to 'Back', stats_path %>

app/views/stats/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Userid:</strong>
  <%= @stat.userId %>
</p>

<p>
  <strong>Nomssent:</strong>
  <%= @stat.nomsSent %>
</p>

<p>
  <strong>Nomsreceived:</strong>
  <%= @stat.nomsReceived %>
</p>

<p>
  <strong>Mvpwins:</strong>
  <%= @stat.mvpWins %>
</p>

<%= link_to 'Edit', edit_stat_path(@stat) %> |
<%= link_to 'Back', stats_path %>